name: build_rPackages

on:
  push:
    branches: [master, main]
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_PAT }}
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set branch_date as today
        id: set_date
        run: echo "branch_date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Check date
        run: echo ${{ env.branch_date }}

      - name: Update default.nix
        run: |
          sed -i 's/REPLACE_DATE/${{ env.branch_date }}/g' default.nix

      - name: Build on date ${{ github.event.client_payload.ref_name }} (default1.nix)
        run: |
          nix-build --max-jobs 1 --cores 2 default1.nix --keep-going 2>&1 | tee -a build-linux.log

      - name: Build on date ${{ github.event.client_payload.ref_name }} (default2.nix)
        run: |
          nix-build --max-jobs 1 --cores 2 default2.nix --keep-going 2>&1 | tee -a build-linux.log

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-log
          path: build-linux.log
        continue-on-error: true

  build-on-macos:
    name: Trigger build for available dates on aarch64-darwin
    runs-on: macos-latest
    needs: build-on-ubuntu

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Set branch_date as today
        id: set_date
        run: echo "branch_date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Check date
        run: echo ${{ env.branch_date }}

      - name: Update default.nix
        run: |
          sed -i '' 's/REPLACE_DATE/${{ env.branch_date }}/g' default.nix

      - name: Build on date ${{ github.event.client_payload.ref_name }} (default1.nix)
        run: |
          nix-build --max-jobs 1 --cores 2 default1.nix --keep-going 2>&1 | tee -a build-darwin.log

      - name: Build on date ${{ github.event.client_payload.ref_name }} (default2.nix)
        run: |
          nix-build --max-jobs 1 --cores 2 default2.nix --keep-going 2>&1 | tee -a build-darwin.log

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-darwin-log
          path: build-darwin.log
        continue-on-error: true

#  clone-and-open-pr:
#      name: Clone rix and open PR
#      runs-on: ubuntu-latest
#      needs: build-on-macos
#
#      steps:
#        - name: Clone rix and open PR
#          run: |
#            curl -X POST \
#            -H "Authorization: token ${{ secrets.UPDATE_AVAILABLE_DATES }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/ropensci/rix/dispatches \
#            -d '{
#              "event_type": "trigger-workflow"
#            }'
