name: Build R Packages in Chunks

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 * *'   # Monthly on the 1st at 00:00 UTC

# (PAT is used, so these permissions blocks are not strictly required, but harmless.)
permissions:
  contents: read
  pull-requests: read

jobs:
  setup-chunks:
    runs-on: ubuntu-latest
    outputs:
      branch_date: ${{ steps.set_date.outputs.branch_date }}
      chunks: ${{ steps.split.outputs.chunks }}
    steps:
      - name: Verify PAT secret exists (early fail if missing)
        run: |
          if [ -z "${{ secrets.MY_PAT }}" ]; then
            echo "ERROR: secrets.MY_PAT is not defined in this (source) repository."
            echo "Define a PAT with 'repo' scope (classic) or fine-grained read/write contents access to rstats-on-nix/nixpkgs."
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Set branch_date as today
        id: set_date
        run: |
          branch_date=$(date '+%Y-%m-%d')
          echo "branch_date=$branch_date" >> $GITHUB_OUTPUT

      - name: Fetch rPackages attribute names without evaluating broken packages
        run: |
          nix eval --json \
            github:rstats-on-nix/nixpkgs/${{ steps.set_date.outputs.branch_date }}#rPackages \
            --apply builtins.attrNames > rpackages.json
          jq -r '.[]' rpackages.json > rpackages.csv
          echo "Total packages:"
          wc -l rpackages.csv

      - name: Limit to first 10 packages (testing)
        run: |
          head -n 10 rpackages.csv > rpackages.first10
          mv rpackages.first10 rpackages.csv
          echo "Selected package count:"
          wc -l rpackages.csv

      - name: Split packages into chunks of 2 (numeric suffix for chunk number)
        id: split
        run: |
          mkdir chunks
          split -l 2 -d -a 3 rpackages.csv chunks/chunk_
          chunks_json=$(printf '%s\n' chunks/chunk_* | jq -R -s -c 'split("\n")[:-1]')
          echo "chunks=$chunks_json" >> $GITHUB_OUTPUT
          echo "Chunk files:"
          printf '%s\n' chunks/chunk_*

      - name: Upload chunk files
        uses: actions/upload-artifact@v4
        with:
          name: package-chunks
          path: chunks/

  build-chunk:
    needs: setup-chunks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        chunk_file: ${{ fromJson(needs.setup-chunks.outputs.chunks) }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Download chunk file
        uses: actions/download-artifact@v4
        with:
          name: package-chunks
          path: chunks

      - name: Derive chunk ID (basename without path)
        id: chunk_id
        run: |
          fname=$(basename "${{ matrix.chunk_file }}")
          echo "id=$fname" >> $GITHUB_OUTPUT
          echo "Using chunk id: $fname"

      - name: Build packages (parallel via Nix internal parallelism)
        continue-on-error: true
        run: |
          branch_date="${{ needs.setup-chunks.outputs.branch_date }}"
          chunk_id="${{ steps.chunk_id.outputs.id }}"
          logfile="logs/build-${{ matrix.os }}-${chunk_id}-${branch_date}-${{ github.run_id }}.log"
          mkdir -p logs
          while read pkg; do
            echo "=== Building $pkg ===" | tee -a "$logfile"
            nix build -j auto --keep-going "github:rstats-on-nix/nixpkgs/${branch_date}#rPackages.$pkg" \
              >>"$logfile" 2>&1 || echo "removing $pkg" >>"$logfile"
          done < "${{ matrix.chunk_file }}"

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-${{ steps.chunk_id.outputs.id }}
          path: logs/

  collect-results:
    needs: build-chunk
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Aggregate failed packages
        id: aggregate
        run: |
          mkdir -p failed
          find artifacts -type f -name "*.log" -exec grep -E 'removing .*' {} \; \
            | sed -E 's/^removing //' \
            | sort -u > failed/failed.txt || true
          echo "Failed packages (if any):"
          cat failed/failed.txt || true

      - name: Prepare PR body (summary only)
        id: pr_body
        run: |
          echo "<details><summary>Failed packages</summary>" > pr_body.txt
          echo "" >> pr_body.txt
          if [ -s failed/failed.txt ]; then
            cat failed/failed.txt >> pr_body.txt
          else
            echo "All packages built successfully." >> pr_body.txt
          fi
          echo "" >> pr_body.txt
          echo "</details>" >> pr_body.txt
          body=$(cat pr_body.txt)
          body_json=$(jq -Rs . <<< "$body")
          echo "body=$body_json" >> $GITHUB_OUTPUT

      - name: Checkout target repo (master) with PAT
        uses: actions/checkout@v4
        with:
          repository: rstats-on-nix/nixpkgs
          ref: master
          path: target-nixpkgs
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}

      - name: Import JSON files from dated branch
        working-directory: target-nixpkgs
        run: |
          date_branch="${{ needs.setup-chunks.outputs.branch_date }}"
          echo "Importing JSON from branch: $date_branch"
          if git ls-remote --exit-code origin "refs/heads/$date_branch" >/dev/null 2>&1; then
            git fetch origin "$date_branch:$date_branch"
            git checkout master
            git checkout "$date_branch" -- pkgs/development/r-modules/bioc-annotation-packages.json \
                                        pkgs/development/r-modules/bioc-experiment-packages.json \
                                        pkgs/development/r-modules/bioc-packages.json \
                                        pkgs/development/r-modules/cran-packages.json || true
            echo "Imported JSON files from $date_branch."
          else
            echo "No dated branch $date_branch found; skipping JSON import."
          fi
          ls -lh pkgs/development/r-modules/*.json || true

      - name: Create PR (JSON updates only)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MY_PAT }}
          path: target-nixpkgs
          add-paths: |
            pkgs/development/r-modules/bioc-annotation-packages.json
            pkgs/development/r-modules/bioc-experiment-packages.json
            pkgs/development/r-modules/bioc-packages.json
            pkgs/development/r-modules/cran-packages.json
          base: master
          branch: update-r-modules-${{ needs.setup-chunks.outputs.branch_date }}
          title: "Update R module JSONs for ${{ needs.setup-chunks.outputs.branch_date }}"
          body: ${{ steps.pr_body.outputs.body }}
