name: Cleanup Old Logs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old log files
        run: |
          find . -type f -name "build-*.log" | while read file; do
            # Extract date from filename (YYYY-MM-DD format)
            file_date=$(echo "$file" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}')
            if [[ -n "$file_date" ]]; then
              # Convert to UNIX timestamp
              file_timestamp=$(date -d "$file_date" +%s)
              current_timestamp=$(date +%s)
              age=$(( (current_timestamp - file_timestamp) / 86400 )) # Convert seconds to days
              if [[ $age -gt 7 ]]; then
                echo "Deleting $file (Age: $age days)"
                rm "$file"
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No old files to delete."
          else
            git commit -m "Remove log files older than 7 days"
            git push
          fi
