name: Check logs for failed packages

on:
  workflow_run:
    workflows: ["build_rPackages"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build log
        uses: actions/download-artifact@v4
        with:
          name: build-linux-log
        continue-on-error: true

      - name: Check for failed builds
        run: |
          grep -oE 'rPackages\.[a-zA-Z0-9_]+' build-linux.log | sort -u > failed.txt

          if [ -s failed.txt ]; then
            echo "Some packages failed to build on Linux:"
            cat failed.txt
            exit 1
          else
            echo "All packages built successfully."
          fi

      - name: Download build log
        uses: actions/download-artifact@v4
        with:
          name: build-darwin-log
        continue-on-error: true

      - name: Check for failed builds
        run: |
          grep -oE 'rPackages\.[a-zA-Z0-9_]+' build-darwin.log | sort -u > failed.txt

          if [ -s failed.txt ]; then
            echo "Some packages failed to build on Darwin:"
            cat failed.txt
            exit 1
          else
            echo "All packages built successfully."
          fi
