# Inspired by the template in the {targets} package
# https://github.com/ropensci/targets/blob/3b16f37ba5cdca710adbb81c2301f6b1d7432cfb/inst/templates/github_actions.yaml

name: run-pipeline

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  targets:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
  
      - name: Use rstats-on-nix cache
        uses: cachix/cachix-action@v14
        with:
          name: rstats-on-nix

      - name: Build development environment
        run: |
          nix-build shell.nix

      - name: Quarto Render table
        run: |
          nix-shell shell.nix --run "quarto render index.qmd"

      - name: Upload rendered paper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Rendered table"
          git push origin master
  
