name: Open PR

on:
  workflow_run:
    workflows:
      - "Build rPackages1"
      - "Build rPackages2"
    types:
      - completed

jobs:
  clone-and-open-pr:
    runs-on: ubuntu-latest
    needs:
      - build_rPackages1
      - build_rPackages2
    steps:
       - run: echo "hello"
#      - name: Clone rix and open PR
#        run: |
#          curl -X POST \
#            -H "Authorization: token ${{ secrets.UPDATE_AVAILABLE_DATES }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/ropensci/rix/dispatches \
#            -d '{
#              "event_type": "trigger-workflow"
#            }'
