name: Open PR

on:
  push:
    branches: [master, main]
  schedule:
    - cron: '0 12 * * 2' # only run on tuesday to let other workflows finish

jobs:
  clone-and-open-pr:
    runs-on: ubuntu-latest
    needs:
      - build_rPackages1
      - build_rPackages2
    steps:
       - run: echo "hello"
       - uses: actions/download-artifact@v4
         with:
           name: build-linux1-log
           github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
           repository: rstats-on-nix/build_rPackages
       - uses: actions/download-artifact@v4
         with:
           name: build-darwin1-log
           github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
           repository: rstats-on-nix/build_rPackages
#      - name: Clone rix and open PR
#        run: |
#          curl -X POST \
#            -H "Authorization: token ${{ secrets.UPDATE_AVAILABLE_DATES }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/ropensci/rix/dispatches \
#            -d '{
#              "event_type": "trigger-workflow"
#            }'
